import type { GenerateJSONOptions, GenerateTextOptions, LLMProvider, Usage } from "./types";

// Zero-cost provider: returns canned data that satisfies the requested JSON
// schema, with no model call at all. For testing UI / editing / persistence.

const ZERO: Usage = { inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0 };

type JsonSchema = {
  type?: string;
  properties?: Record<string, JsonSchema>;
  items?: JsonSchema;
};

function mockString(name: string): string {
  switch (name) {
    case "title":
      return "The Mock Manuscript";
    case "logline":
      return "A test protagonist confronts a test conflict in a test world.";
    case "genre":
      return "Literary fiction";
    case "pov":
      return "Third person limited";
    case "tense":
      return "Past";
    case "tone":
      return "Contemplative";
    case "setting":
      return "An unnamed coastal town";
    case "name":
      return "Alex Rivers";
    case "role":
      return "protagonist";
    case "description":
      return "A placeholder description generated by the mock backend (no API call).";
    case "outline":
      return "A placeholder, beat-by-beat outline produced by the mock backend so you can exercise the editor without spending anything. The protagonist wants something, an obstacle gets in the way, and the situation changes by the end.";
    default:
      return "Mock content (no API call).";
  }
}

function fake(schema: JsonSchema, name = "field"): unknown {
  switch (schema.type) {
    case "object": {
      const out: Record<string, unknown> = {};
      const props = schema.properties ?? {};
      for (const key of Object.keys(props)) out[key] = fake(props[key], key);
      return out;
    }
    case "array": {
      const items = schema.items ?? {};
      return [0, 1, 2].map((i) => {
        const v = fake(items, name);
        // Make array items distinguishable (e.g. chapter titles).
        if (v && typeof v === "object" && typeof (v as Record<string, unknown>).title === "string") {
          (v as Record<string, unknown>).title = `${(v as Record<string, unknown>).title as string} ${i + 1}`;
        }
        return v;
      });
    }
    case "number":
    case "integer":
      return 1;
    case "boolean":
      return true;
    case "string":
    default:
      return mockString(name);
  }
}

export class MockProvider implements LLMProvider {
  readonly name = "mock";

  async generateText(_opts: GenerateTextOptions) {
    void _opts;
    return {
      text: "Mock chapter text. No model was called — this is canned output for testing the flow.",
      usage: ZERO,
    };
  }

  async generateJSON(opts: GenerateJSONOptions) {
    const data = fake(opts.jsonSchema as JsonSchema);
    return { data, raw: JSON.stringify(data), usage: ZERO };
  }
}
